User creation
WildCodeSchool/tours-php-2103-project3-citoyelles pull request #19
Opened 2021-07-02 08:23 UTC by AmanelGau

2021-07-02 09:25 UTC, Orijma commented
Symfony sends me: "Impossible to access an attribute ("roles") on a null variable."

2021-07-05 07:22 UTC, arnaud-blanc approved these changes

2021-07-05 09:56 UTC, RomainClair requested changes
You migration file is incompatible with a database in the dev state

2021-07-05 09:56 UTC, RomainClair commented on src/Security/AppAuthenticator.php
> +        throw new Exception('TODO: provide a valid redirect inside ' . __FILE__);
You must choose the route to redirect to after a successful login by a user that access directly to the login page

2021-07-08 08:12 UTC, arnaud-blanc approved these changes

2021-07-08 08:29 UTC, RomainClair approved these changes

2021-07-08 08:29 UTC, merged