changes in username fields in the form
WildCodeSchool/tours-php-2103-project3-citoyelles pull request #38
Opened 2021-07-16 09:03 UTC by AmanelGau

2021-07-16 09:18 UTC, arnaud-blanc commented on src/Service/UserService.php
> +            $errors[] = "Veuillez entré un nouveau nom d'utilisateur";
"entré" => "entrer"

2021-07-16 09:30 UTC, arnaud-blanc approved these changes
Stephane also did something interesting, if you want to ask about additional things!

2021-07-16 10:17 UTC, RomainClair requested changes
You probably should deal with form the symfony way (in a symfony project)
Take a look at : https://symfony.com/doc/current/forms.html

2021-07-16 10:17 UTC, RomainClair commented on src/Controller/SecurityController.php
>          $userService = new UserService();
Objects behind forms are not services.
Is there a reason not to use the User object this forms seems to edit ?

2021-07-16 10:17 UTC, RomainClair commented on src/Controller/SecurityController.php
>              } elseif ($errors) {
It's a strange idea to bypass the Symfony Form component and it's validation tools in a symfony prooject.
You probably should use constraints in the User entity to validate your form edition.

2021-07-19 09:23 UTC, arnaud-blanc commented on src/Controller/SecurityController.php
> +                $this->addFlash('notice', 'Aucune modification détecter, veuillez remplir les champs correctement !');
détecter => détectée

2021-07-19 10:03 UTC, arnaud-blanc requested changes
Reminder: the administrator is not comfortable with computers!
It will be essential to clearly explain the steps to be taken to :
- change username
- change password
These are two different things.
For this, it is necessary to bring an explanatory note to the administrator.

2021-07-23 11:58 UTC, Orijma approved these changes

2021-07-23 12:26 UTC, RomainClair reviewed
Check the UserPassword constraints (https://symfony.com/doc/current/reference/constraints/UserPassword.html) which can be useful in this particular case
You should make sure to "forget" the plainPassword after encoding by completing the User::eraseCredential method and call it in you controller after encoding.

2021-07-23 12:27 UTC, RomainClair approved these changes
Check the UserPassword constraints (https://symfony.com/doc/current/reference/constraints/UserPassword.html) which can be useful in this particular case
You should make sure to "forget" the plainPassword after encoding by completing the User::eraseCredential method and call it in you controller after encoding.

2021-07-26 06:54 UTC, RomainClair submitted a review, later dismissed

2021-07-28 08:19 UTC, arnaud-blanc approved these changes

2021-07-28 08:25 UTC, Orijma approved these changes

2021-07-28 08:27 UTC, RomainClair approved these changes

2021-07-28 08:27 UTC, merged